// <auto-generated />
using System;
using CRUD_Application_Angular_Asp_Net_sql.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Application_Angular_Asp_Net_sql.Migrations
{
    [DbContext(typeof(StudentDbcontext))]
    [Migration("20260206095827_RoleBasedLoginaddkey")]
    partial class RoleBasedLoginaddkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Application_Angular_Asp_Net_sql.Model.LoginsTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sujalgopani@gmail.com",
                            Password = "pass123",
                            RoleId = 1,
                            Uname = "Sujal"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sujalgopani@gmail.com",
                            Password = "pass123",
                            RoleId = 2,
                            Uname = "Admin"
                        });
                });

            modelBuilder.Entity("CRUD_Application_Angular_Asp_Net_sql.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("URole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleTbl");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            URole = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            URole = "Student"
                        });
                });

            modelBuilder.Entity("CRUD_Application_Angular_Asp_Net_sql.Model.StudnetMaster", b =>
                {
                    b.Property<int>("studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentid"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("contact")
                        .HasColumnType("bigint");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("studentname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("studentid");

                    b.ToTable("StudentMaster");

                    b.HasData(
                        new
                        {
                            studentid = 1,
                            DOB = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            address = "Test Address",
                            city = "Surat",
                            comment = "Default test data",
                            contact = 9999999999L,
                            country = "India",
                            cources = "Angular + ASP.NET",
                            email = "test@student.com",
                            state = "Gujarat",
                            studentname = "Test Student"
                        });
                });

            modelBuilder.Entity("CRUD_Application_Angular_Asp_Net_sql.Model.LoginsTbl", b =>
                {
                    b.HasOne("CRUD_Application_Angular_Asp_Net_sql.Model.Role", "Role")
                        .WithMany("Logins")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRUD_Application_Angular_Asp_Net_sql.Model.Role", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
